name: "Labeler"
on:
  pull_request_target:

permissions:
  contents: read

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Labels
        uses: actions/labeler@v6
        with:
          sync-labels: false
